import { create } from 'zustand'

const translations = {
  en: {
    home: 'Home', banks: 'Banks', analytics: 'Analytics',
    savings: 'Savings', advisor: 'Advisor', settings: 'Settings',
    goodMorning: 'Good morning', financialHealth: 'Financial Health Score',
    simulatedBalance: 'Simulated Balance', savedThisMonth: 'saved this month via round-up',
    quickActions: 'Quick Actions', recentTransactions: 'Recent Transactions',
    seeAll: 'See all', openAccount: 'Open Account', compareBanks: 'Compare Banks',
    askAdvisor: 'Ask Advisor', startSaving: 'Start Saving',
    jamaicaBanks: 'Jamaican Banks', compareFind: 'Compare and find the right bank for you',
    analyticsTitle: 'Analytics', spendingBreakdown: 'Your spending breakdown',
    smartSavings: 'Smart Savings', roundUpAuto: 'Round-up every transaction automatically',
    totalSaved: 'Total Saved This Month', projectedMonthly: 'Projected Monthly',
    projectedYearly: 'Projected Yearly', settingsTitle: 'Settings',
    customise: 'Customise your NEXUS experience', theme: 'Theme',
    darkGold: 'Dark Gold', lightMode: 'Light Mode', language: 'Language',
    notifications: 'Notifications', allEnabled: 'All enabled',
    biometric: 'Biometric Login', twoFactor: 'Two-Factor Auth',
    signOut: 'Sign Out', appVersion: 'App Version', builtBy: 'Built by',
    goodStanding: 'Good Standing', predictedNext: 'Predicted Next',
    thisMonth: 'This Month', aiInsights: 'AI Insights',
    recentRoundUps: 'Recent Round-Ups', roundUpSavings: 'Round-Up Savings',
    autoSave: 'Auto-save spare change', autoInvest: 'Auto-Invest Savings',
    monthlyPlan: 'Monthly into selected plan', roundUpNearest: 'Round up to nearest:',
    selectPlan: 'Select investment plan:', preferences: 'Preferences',
    security: 'Security', about: 'About',
  },
  es: {
    home: 'Inicio', banks: 'Bancos', analytics: 'Análisis',
    savings: 'Ahorros', advisor: 'Asesor', settings: 'Ajustes',
    goodMorning: 'Buenos días', financialHealth: 'Puntuación de Salud Financiera',
    simulatedBalance: 'Saldo Simulado', savedThisMonth: 'ahorrado este mes via redondeo',
    quickActions: 'Acciones Rápidas', recentTransactions: 'Transacciones Recientes',
    seeAll: 'Ver todo', openAccount: 'Abrir Cuenta', compareBanks: 'Comparar Bancos',
    askAdvisor: 'Preguntar Asesor', startSaving: 'Empezar a Ahorrar',
    jamaicaBanks: 'Bancos de Jamaica', compareFind: 'Compara y encuentra el banco ideal',
    analyticsTitle: 'Análisis', spendingBreakdown: 'Resumen de gastos',
    smartSavings: 'Ahorros Inteligentes', roundUpAuto: 'Redondea cada transacción automáticamente',
    totalSaved: 'Total Ahorrado Este Mes', projectedMonthly: 'Proyección Mensual',
    projectedYearly: 'Proyección Anual', settingsTitle: 'Ajustes',
    customise: 'Personaliza tu experiencia NEXUS', theme: 'Tema',
    darkGold: 'Oro Oscuro', lightMode: 'Modo Claro', language: 'Idioma',
    notifications: 'Notificaciones', allEnabled: 'Todo activado',
    biometric: 'Inicio Biométrico', twoFactor: 'Autenticación de Dos Factores',
    signOut: 'Cerrar Sesión', appVersion: 'Versión', builtBy: 'Creado por',
    goodStanding: 'Buen Estado', predictedNext: 'Próximo Mes',
    thisMonth: 'Este Mes', aiInsights: 'Perspectivas IA',
    recentRoundUps: 'Redondeos Recientes', roundUpSavings: 'Ahorro por Redondeo',
    autoSave: 'Guarda el cambio automáticamente', autoInvest: 'Auto-Invertir Ahorros',
    monthlyPlan: 'Mensual en el plan seleccionado', roundUpNearest: 'Redondear al más cercano:',
    selectPlan: 'Seleccionar plan de inversión:', preferences: 'Preferencias',
    security: 'Seguridad', about: 'Acerca de',
  },
  fr: {
    home: 'Accueil', banks: 'Banques', analytics: 'Analyses',
    savings: 'Épargne', advisor: 'Conseiller', settings: 'Paramètres',
    goodMorning: 'Bonjour', financialHealth: 'Score de Santé Financière',
    simulatedBalance: 'Solde Simulé', savedThisMonth: 'économisé ce mois via arrondi',
    quickActions: 'Actions Rapides', recentTransactions: 'Transactions Récentes',
    seeAll: 'Voir tout', openAccount: 'Ouvrir un Compte', compareBanks: 'Comparer les Banques',
    askAdvisor: 'Demander Conseiller', startSaving: 'Commencer à Épargner',
    jamaicaBanks: 'Banques de Jamaïque', compareFind: 'Comparez et trouvez la bonne banque',
    analyticsTitle: 'Analyses', spendingBreakdown: 'Détail des dépenses',
    smartSavings: 'Épargne Intelligente', roundUpAuto: 'Arrondissez chaque transaction automatiquement',
    totalSaved: 'Total Épargné Ce Mois', projectedMonthly: 'Projection Mensuelle',
    projectedYearly: 'Projection Annuelle', settingsTitle: 'Paramètres',
    customise: 'Personnalisez votre expérience NEXUS', theme: 'Thème',
    darkGold: 'Or Sombre', lightMode: 'Mode Clair', language: 'Langue',
    notifications: 'Notifications', allEnabled: 'Tout activé',
    biometric: 'Connexion Biométrique', twoFactor: 'Authentification à Deux Facteurs',
    signOut: 'Se Déconnecter', appVersion: 'Version', builtBy: 'Créé par',
    goodStanding: 'Bonne Position', predictedNext: 'Mois Prochain',
    thisMonth: 'Ce Mois', aiInsights: 'Aperçus IA',
    recentRoundUps: 'Arrondis Récents', roundUpSavings: 'Épargne par Arrondi',
    autoSave: 'Économise automatiquement la monnaie', autoInvest: 'Auto-Investir Épargne',
    monthlyPlan: 'Mensuel dans le plan sélectionné', roundUpNearest: 'Arrondir au plus proche:',
    selectPlan: "Sélectionner le plan d'investissement:", preferences: 'Préférences',
    security: 'Sécurité', about: 'À Propos',
  },
  nl: {
    home: 'Thuis', banks: 'Banken', analytics: 'Analyse',
    savings: 'Sparen', advisor: 'Adviseur', settings: 'Instellingen',
    goodMorning: 'Goedemorgen', financialHealth: 'Financiële Gezondheidsscore',
    simulatedBalance: 'Gesimuleerd Saldo', savedThisMonth: 'gespaard deze maand via afronding',
    quickActions: 'Snelle Acties', recentTransactions: 'Recente Transacties',
    seeAll: 'Alles zien', openAccount: 'Account Openen', compareBanks: 'Banken Vergelijken',
    askAdvisor: 'Vraag Adviseur', startSaving: 'Begin met Sparen',
    jamaicaBanks: 'Jamaicaanse Banken', compareFind: 'Vergelijk en vind de juiste bank',
    analyticsTitle: 'Analyse', spendingBreakdown: 'Uw uitgavenoverzicht',
    smartSavings: 'Slim Sparen', roundUpAuto: 'Rond elke transactie automatisch af',
    totalSaved: 'Totaal Gespaard Deze Maand', projectedMonthly: 'Maandelijkse Projectie',
    projectedYearly: 'Jaarlijkse Projectie', settingsTitle: 'Instellingen',
    customise: 'Pas uw NEXUS-ervaring aan', theme: 'Thema',
    darkGold: 'Donker Goud', lightMode: 'Lichte Modus', language: 'Taal',
    notifications: 'Meldingen', allEnabled: 'Alles ingeschakeld',
    biometric: 'Biometrische Login', twoFactor: 'Twee-Factor Authenticatie',
    signOut: 'Uitloggen', appVersion: 'Versie', builtBy: 'Gebouwd door',
    goodStanding: 'Goede Standing', predictedNext: 'Volgende Maand',
    thisMonth: 'Deze Maand', aiInsights: 'AI Inzichten',
    recentRoundUps: 'Recente Afrondingen', roundUpSavings: 'Sparen door Afronding',
    autoSave: 'Sla automatisch wisselgeld op', autoInvest: 'Auto-Investeer Spaargeld',
    monthlyPlan: 'Maandelijks in geselecteerd plan', roundUpNearest: 'Afgerond naar dichtstbijzijnde:',
    selectPlan: 'Selecteer investeringsplan:', preferences: 'Voorkeuren',
    security: 'Beveiliging', about: 'Over',
  },
  pt: {
    home: 'Início', banks: 'Bancos', analytics: 'Análises',
    savings: 'Poupanças', advisor: 'Conselheiro', settings: 'Definições',
    goodMorning: 'Bom dia', financialHealth: 'Pontuação de Saúde Financeira',
    simulatedBalance: 'Saldo Simulado', savedThisMonth: 'poupado este mês via arredondamento',
    quickActions: 'Ações Rápidas', recentTransactions: 'Transações Recentes',
    seeAll: 'Ver tudo', openAccount: 'Abrir Conta', compareBanks: 'Comparar Bancos',
    askAdvisor: 'Perguntar Conselheiro', startSaving: 'Começar a Poupar',
    jamaicaBanks: 'Bancos da Jamaica', compareFind: 'Compare e encontre o banco certo',
    analyticsTitle: 'Análises', spendingBreakdown: 'Resumo dos gastos',
    smartSavings: 'Poupança Inteligente', roundUpAuto: 'Arredonde cada transação automaticamente',
    totalSaved: 'Total Poupado Este Mês', projectedMonthly: 'Projeção Mensal',
    projectedYearly: 'Projeção Anual', settingsTitle: 'Definições',
    customise: 'Personalize a sua experiência NEXUS', theme: 'Tema',
    darkGold: 'Ouro Escuro', lightMode: 'Modo Claro', language: 'Idioma',
    notifications: 'Notificações', allEnabled: 'Tudo ativado',
    biometric: 'Login Biométrico', twoFactor: 'Autenticação de Dois Fatores',
    signOut: 'Sair', appVersion: 'Versão', builtBy: 'Criado por',
    goodStanding: 'Boa Situação', predictedNext: 'Próximo Mês',
    thisMonth: 'Este Mês', aiInsights: 'Perspetivas IA',
    recentRoundUps: 'Arredondamentos Recentes', roundUpSavings: 'Poupança por Arredondamento',
    autoSave: 'Guarda automaticamente o troco', autoInvest: 'Auto-Investir Poupanças',
    monthlyPlan: 'Mensal no plano selecionado', roundUpNearest: 'Arredondar para o mais próximo:',
    selectPlan: 'Selecionar plano de investimento:', preferences: 'Preferências',
    security: 'Segurança', about: 'Sobre',
  },
  de: {
    home: 'Startseite', banks: 'Banken', analytics: 'Analytik',
    savings: 'Ersparnisse', advisor: 'Berater', settings: 'Einstellungen',
    goodMorning: 'Guten Morgen', financialHealth: 'Finanzielle Gesundheitspunktzahl',
    simulatedBalance: 'Simuliertes Guthaben', savedThisMonth: 'diesen Monat via Aufrundung gespart',
    quickActions: 'Schnellaktionen', recentTransactions: 'Letzte Transaktionen',
    seeAll: 'Alle sehen', openAccount: 'Konto Eröffnen', compareBanks: 'Banken Vergleichen',
    askAdvisor: 'Berater Fragen', startSaving: 'Sparen Beginnen',
    jamaicaBanks: 'Jamaikanische Banken', compareFind: 'Vergleichen Sie und finden Sie die richtige Bank',
    analyticsTitle: 'Analytik', spendingBreakdown: 'Ihre Ausgabenübersicht',
    smartSavings: 'Intelligentes Sparen', roundUpAuto: 'Runden Sie jede Transaktion automatisch auf',
    totalSaved: 'Gesamt Gespart Diesen Monat', projectedMonthly: 'Monatliche Projektion',
    projectedYearly: 'Jährliche Projektion', settingsTitle: 'Einstellungen',
    customise: 'Passen Sie Ihr NEXUS-Erlebnis an', theme: 'Thema',
    darkGold: 'Dunkles Gold', lightMode: 'Heller Modus', language: 'Sprache',
    notifications: 'Benachrichtigungen', allEnabled: 'Alles aktiviert',
    biometric: 'Biometrischer Login', twoFactor: 'Zwei-Faktor-Authentifizierung',
    signOut: 'Abmelden', appVersion: 'Version', builtBy: 'Erstellt von',
    goodStanding: 'Guter Status', predictedNext: 'Nächsten Monat',
    thisMonth: 'Diesen Monat', aiInsights: 'KI-Einblicke',
    recentRoundUps: 'Letzte Aufrundungen', roundUpSavings: 'Sparen durch Aufrundung',
    autoSave: 'Speichert automatisch Wechselgeld', autoInvest: 'Auto-Investieren Ersparnisse',
    monthlyPlan: 'Monatlich in ausgewähltem Plan', roundUpNearest: 'Aufrunden auf nächste:',
    selectPlan: 'Investitionsplan auswählen:', preferences: 'Einstellungen',
    security: 'Sicherheit', about: 'Über',
  },
  zh: {
    home: '主页', banks: '银行', analytics: '分析',
    savings: '储蓄', advisor: '顾问', settings: '设置',
    goodMorning: '早上好', financialHealth: '财务健康评分',
    simulatedBalance: '模拟余额', savedThisMonth: '本月通过四舍五入节省',
    quickActions: '快速操作', recentTransactions: '最近交易',
    seeAll: '查看全部', openAccount: '开户', compareBanks: '比较银行',
    askAdvisor: '咨询顾问', startSaving: '开始储蓄',
    jamaicaBanks: '牙买加银行', compareFind: '比较并找到适合您的银行',
    analyticsTitle: '分析', spendingBreakdown: '您的支出明细',
    smartSavings: '智能储蓄', roundUpAuto: '自动对每笔交易进行四舍五入',
    totalSaved: '本月总储蓄', projectedMonthly: '每月预测',
    projectedYearly: '每年预测', settingsTitle: '设置',
    customise: '自定义您的NEXUS体验', theme: '主题',
    darkGold: '暗金', lightMode: '浅色模式', language: '语言',
    notifications: '通知', allEnabled: '全部启用',
    biometric: '生物识别登录', twoFactor: '双因素认证',
    signOut: '退出登录', appVersion: '版本', builtBy: '创建者',
    goodStanding: '良好状态', predictedNext: '下个月',
    thisMonth: '本月', aiInsights: 'AI洞察',
    recentRoundUps: '最近的四舍五入', roundUpSavings: '四舍五入储蓄',
    autoSave: '自动保存零钱', autoInvest: '自动投资储蓄',
    monthlyPlan: '每月投入选定计划', roundUpNearest: '四舍五入到最近:',
    selectPlan: '选择投资计划:', preferences: '偏好设置',
    security: '安全', about: '关于',
  },
  hi: {
    home: 'होम', banks: 'बैंक', analytics: 'विश्लेषण',
    savings: 'बचत', advisor: 'सलाहकार', settings: 'सेटिंग्स',
    goodMorning: 'सुप्रभात', financialHealth: 'वित्तीय स्वास्थ्य स्कोर',
    simulatedBalance: 'अनुकरण शेष', savedThisMonth: 'इस महीने राउंड-अप के माध्यम से बचाया',
    quickActions: 'त्वरित क्रियाएं', recentTransactions: 'हाल के लेनदेन',
    seeAll: 'सभी देखें', openAccount: 'खाता खोलें', compareBanks: 'बैंक तुलना करें',
    askAdvisor: 'सलाहकार से पूछें', startSaving: 'बचत शुरू करें',
    jamaicaBanks: 'जमैका बैंक', compareFind: 'सही बैंक खोजें और तुलना करें',
    analyticsTitle: 'विश्लेषण', spendingBreakdown: 'आपका खर्च विवरण',
    smartSavings: 'स्मार्ट बचत', roundUpAuto: 'हर लेनदेन को स्वचालित रूप से राउंड अप करें',
    totalSaved: 'इस महीने कुल बचत', projectedMonthly: 'मासिक अनुमान',
    projectedYearly: 'वार्षिक अनुमान', settingsTitle: 'सेटिंग्स',
    customise: 'अपना NEXUS अनुभव अनुकूलित करें', theme: 'थीम',
    darkGold: 'डार्क गोल्ड', lightMode: 'लाइट मोड', language: 'भाषा',
    notifications: 'सूचनाएं', allEnabled: 'सब सक्षम',
    biometric: 'बायोमेट्रिक लॉगिन', twoFactor: 'दो-कारक प्रमाणीकरण',
    signOut: 'साइन आउट', appVersion: 'संस्करण', builtBy: 'निर्मित द्वारा',
    goodStanding: 'अच्छी स्थिति', predictedNext: 'अगला महीना',
    thisMonth: 'इस महीने', aiInsights: 'AI अंतर्दृष्टि',
    recentRoundUps: 'हालिया राउंड-अप', roundUpSavings: 'राउंड-अप बचत',
    autoSave: 'स्वचालित रूप से बचाएं', autoInvest: 'ऑटो-इन्वेस्ट बचत',
    monthlyPlan: 'मासिक चयनित योजना में', roundUpNearest: 'निकटतम तक राउंड अप:',
    selectPlan: 'निवेश योजना चुनें:', preferences: 'प्राथमिकताएं',
    security: 'सुरक्षा', about: 'के बारे में',
  },
  ar: {
    home: 'الرئيسية', banks: 'البنوك', analytics: 'التحليلات',
    savings: 'المدخرات', advisor: 'المستشار', settings: 'الإعدادات',
    goodMorning: 'صباح الخير', financialHealth: 'درجة الصحة المالية',
    simulatedBalance: 'الرصيد المحاكى', savedThisMonth: 'تم توفيره هذا الشهر عبر التقريب',
    quickActions: 'الإجراءات السريعة', recentTransactions: 'المعاملات الأخيرة',
    seeAll: 'عرض الكل', openAccount: 'فتح حساب', compareBanks: 'مقارنة البنوك',
    askAdvisor: 'اسأل المستشار', startSaving: 'ابدأ الادخار',
    jamaicaBanks: 'بنوك جامايكا', compareFind: 'قارن وجد البنك المناسب لك',
    analyticsTitle: 'التحليلات', spendingBreakdown: 'تفاصيل إنفاقك',
    smartSavings: 'الادخار الذكي', roundUpAuto: 'تقريب كل معاملة تلقائياً',
    totalSaved: 'إجمالي المدخرات هذا الشهر', projectedMonthly: 'التوقع الشهري',
    projectedYearly: 'التوقع السنوي', settingsTitle: 'الإعدادات',
    customise: 'خصص تجربة NEXUS الخاصة بك', theme: 'المظهر',
    darkGold: 'ذهبي داكن', lightMode: 'الوضع الفاتح', language: 'اللغة',
    notifications: 'الإشعارات', allEnabled: 'الكل مفعل',
    biometric: 'تسجيل الدخول البيومتري', twoFactor: 'المصادقة الثنائية',
    signOut: 'تسجيل الخروج', appVersion: 'الإصدار', builtBy: 'تم البناء بواسطة',
    goodStanding: 'وضع جيد', predictedNext: 'الشهر القادم',
    thisMonth: 'هذا الشهر', aiInsights: 'رؤى الذكاء الاصطناعي',
    recentRoundUps: 'التقريبات الأخيرة', roundUpSavings: 'الادخار بالتقريب',
    autoSave: 'احفظ الفكة تلقائياً', autoInvest: 'الاستثمار التلقائي للمدخرات',
    monthlyPlan: 'شهرياً في الخطة المختارة', roundUpNearest: 'تقريب إلى أقرب:',
    selectPlan: 'اختر خطة الاستثمار:', preferences: 'التفضيلات',
    security: 'الأمان', about: 'حول',
  },
  ja: {
    home: 'ホーム', banks: '銀行', analytics: '分析',
    savings: '貯蓄', advisor: 'アドバイザー', settings: '設定',
    goodMorning: 'おはようございます', financialHealth: '財務健康スコア',
    simulatedBalance: 'シミュレーション残高', savedThisMonth: '今月の端数貯蓄',
    quickActions: 'クイックアクション', recentTransactions: '最近の取引',
    seeAll: 'すべて見る', openAccount: '口座開設', compareBanks: '銀行比較',
    askAdvisor: 'アドバイザーに相談', startSaving: '貯蓄を始める',
    jamaicaBanks: 'ジャマイカの銀行', compareFind: '最適な銀行を比較して見つける',
    analyticsTitle: '分析', spendingBreakdown: '支出内訳',
    smartSavings: 'スマート貯蓄', roundUpAuto: 'すべての取引を自動的に切り上げる',
    totalSaved: '今月の総貯蓄額', projectedMonthly: '月次予測',
    projectedYearly: '年次予測', settingsTitle: '設定',
    customise: 'NEXUSエクスペリエンスをカスタマイズ', theme: 'テーマ',
    darkGold: 'ダークゴールド', lightMode: 'ライトモード', language: '言語',
    notifications: '通知', allEnabled: 'すべて有効',
    biometric: '生体認証ログイン', twoFactor: '二要素認証',
    signOut: 'サインアウト', appVersion: 'バージョン', builtBy: '開発者',
    goodStanding: '良好な状態', predictedNext: '来月',
    thisMonth: '今月', aiInsights: 'AIインサイト',
    recentRoundUps: '最近の切り上げ', roundUpSavings: '切り上げ貯蓄',
    autoSave: '自動的に端数を保存', autoInvest: '貯蓄を自動投資',
    monthlyPlan: '毎月選択したプランへ', roundUpNearest: '最も近い額に切り上げ:',
    selectPlan: '投資プランを選択:', preferences: '設定',
    security: 'セキュリティ', about: 'について',
  },
}

const useAppStore = create((set) => ({
  theme: 'dark',
  language: 'en',
  translations: translations.en,
  user: {
    name: 'Shantel Brown',
    phone: '876 000 0000',
    email: 'shantel@nexus.jm',
  },
  setUser: (user) => set({ user }),
setTheme: (theme) => set({ theme }),
setLanguage: (lang) => set({ language: lang, translations: translations[lang] || translations.en }),
  }),
)

export default useAppStore
export { translations }